### ISSUE TITLE
Pair lookup with REST doesn't work

### ISSUE THREAD

**Issue by krisu-pl** [Green7/terraswap.js#1]
Hello! First of all, I would like to thank you for this package! Having such an abstraction layer is very useful.

However, provided examples don't seem to work. I suspect REST API for fetching pair addresses is failing. I tried setting up a connection both to `bombay-12` 
```
  URL: 'https://lcd.terra.dev',
  chainID: 'columbus-5',
```
and `columbus-5`, and in both cases it fails.
```
  URL: 'https://bombay-lcd.terra.dev',
  chainID: 'bombay-12',
```

I get an axios error `Error: Request failed with status code 500`, with a message:
```
'rpc error: code = Internal desc = Asset mismatch: contract query failed: unknown request'
```

Do you have an idea what could be the problem?

**Comment by Green7** [comment]
Yes you are right. Terraswap changed something in the contents of the files so my pairFinder is not working properly. I have to check it.

**Comment by Green7** [comment]
Check the new version, it should work.
Pozdrawiam :)

**Comment by krisu-pl** [comment]
Thanks for a super quick update!

Seems to work fine on Testnet, but on Mainnet I still get an error 🤔 
```
message: 'rpc error: code = Internal desc = contract terra156v8s539wtz0sjpn8y8a8lfg8fhmwa7fy22aff: not found: unknown request',
```

Trying with:
```
const lcdConfig = {
  URL: 'https://lcd.terra.dev',
  chainID: 'columbus-5',
};
```
and
```
const res = await terraSwap.querySimulationBySymbol(LUNA, UST, "1000000");
```


Pozdrawiam 🙌

**Comment by krisu-pl** [comment]
Ok, my bad! Forgot to change the network in the constructor
```
new TerraSwap("mainnet", wallet)
```

All good now, thanks!

**Comment by bedrosdaniel** [comment]
![image](https://user-images.githubusercontent.com/91813738/150721164-2644f3e3-fa7f-405e-809e-cb071b2b72b0.png)
Hello devs, I found this error when using this package in chrome browser.

**Comment by Green7** [comment]
@bedrosdaniel this is not a bug. This is normal behavior - read more about the CORS policy. 
In brief: to make request to api.terraswap.io from other website it is necessary that the api.terraswap.io server allows this. 

So if you want to create a website using this library, some corrections would be needed.
If you are making the application for your own purposes, you can turn off the CORS policy in chrome: https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

**Comment by Narukirito** [comment]
![queryerror](https://user-images.githubusercontent.com/49794527/164105458-7cca8d83-0746-471f-a348-bb254352ccdd.JPG)
![terraerr](https://user-images.githubusercontent.com/49794527/164105460-ee25d3d7-0bca-4363-b684-1bbe977e9fe9.JPG)
![pairfinder](https://user-images.githubusercontent.com/49794527/164105707-a9a2e2f8-a836-43b5-9029-4f1feda317aa.JPG)

I created the TerraSwap object to get the price thorugh query and executing a transaction on the mainnet for a swap,but I am getting this error.
How do I troubleshoot this error?

**Comment by Green7** [comment]
I just checked and the bLUNA, LUNA swap works. But I see in your code 4 parameters in function call terraswap.queryReverseSimulationBySymbol(). This function has only 3 parameters. What is 'pp' in your code?

**Comment by Narukirito** [comment]
i was trying to troubleshoot the error and called pp as a PairFinder('mainnet') as I thought it might be a testnet-mainnet token name bug,but no luck
![lublerror](https://user-images.githubusercontent.com/49794527/164316768-760b6be2-882c-4da5-aaef-887f19faf037.JPG)
here is what I get when I call the function like this:
![lublecode](https://user-images.githubusercontent.com/49794527/164317144-77b05702-fc49-4eed-ba1e-360d68a7f0d2.JPG)

**Comment by Green7** [comment]
did you call terraSwap.getPairsInfo (); ?
It is necessary (once at program startup) to get information about contract addresses.

**Comment by Narukirito** [comment]
yes,did that
no luck.
![lublecodet](https://user-images.githubusercontent.com/49794527/164549776-cc3554c0-11f2-4cb1-99ba-c99d1d07d377.JPG)
![lublecmdt](https://user-images.githubusercontent.com/49794527/164549922-e75d283c-acd1-4d69-8f0f-981c06b6d917.JPG)

**Comment by Green7** [comment]
are you using the latest version of the library?
Here is sample code:
``` 
  const lcdConfig = {
    URL: 'https://lcd.terra.dev',
    chainID: 'bombay-12',
    gasPrices: {
      uluna: 0.15,
    },
    gasAdjustment: 1.4,
  };
  const lcdClient = new LCDClient(lcdConfig);

  const wallet = new Wallet(
    lcdClient,
    new MnemonicKey({
      mnemonic: process.env.MNEMONIC,
    }),
  );
  const terraSwap = new TerraSwap('mainnet', wallet);
  await terraSwap.getPairsInfo();
  const res = await terraSwap.querySimulationBySymbol(bLUNA, LUNA, '1000');
  // tslint:disable-next-line:no-console
  console.log(res);
```

Result: ``` { return_amount: '993', spread_amount: '0', commission_amount: '2' }```
So everything works.

**Comment by Narukirito** [comment]
chain ID : 'bombay-12'?
is that right?because that is the only thing that is probably different from my piece of code

**Comment by Green7** [comment]
Rigth, it should be 'columbus-5' for mainnet (bombay-12 is for testnet).  But the code works ok also for columbus-5.
