### ISSUE TITLE
Problem following docs

### ISSUE THREAD

**Issue by CartoshiN** [Green7/terraswap.js#2]
Hi,

Thanks for the package. I've pulled it down and followed what it says. I've added these lines from the docs:

```
    const terraSwap = new TerraSwap('testnet', wallet); 
    const res = await terraSwap.querySimulationBySymbol(LUNA, UST, '1000000');
```

LUNA and UST will be undefined in this case by following the docs directly. I was wondering what should we be putting here to get the likes of querySimulationBySymbol to run? I've tried the likes of: 

`const res = await terraSwap.querySimulationBySymbol("LUNA", "UST", '1000000');`

but had no luck. I was hoping to use terraswap.js to convert a the CW20 token bLuna to the native token UST if that's possible.

Cheers.

**Comment by Green7** [comment]
I guess you forgot to add imports:
For example, to use LUNA, UST you must have import:

`` import { LUNA, UST } from 'terraswap.js'; ``
